server:
  port: ${RUN-PORT}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?currentSchema=${PGSCHEMA}
    username: ${USER}
    password: ${PSSWRD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

scheduled-start-time: 0 0 9 * * *